# Dodoi-lab - Research and Development Laboratory
# Service for interactive development
#
# @author Hudson Schumaker
# @email hudson.schumaker@me.com
#
# Copyright (c) 2025 dodoi-lab. All rights reserved.
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#

services:
  ps2game-shell:
    build: .
    container_name: ps2game-shell
    volumes:
      - .:/usr/src/ps2game
    working_dir: /usr/src/ps2game
    environment:
      - PS2DEV=/usr/local/ps2dev
      - PS2SDK=/usr/local/ps2dev/ps2sdk
      - GSKIT=/usr/local/ps2dev/gsKit
      - PATH=/usr/local/ps2dev/bin:/usr/local/ps2dev/ee/bin:/usr/local/ps2dev/iop/bin:$PATH
    command: /bin/bash
    stdin_open: true
    tty: true
